### ISSUE TITLE
Allow phpunit to Set Up Its Own Tests

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/action-test-php#1]
### Description

I would like the option, similar to [the PHP tests workflow](https://github.com/alleyinteractive/.github/blob/main/.github/workflows/php-tests.yml), to not have GitHub Actions set up the PHP tests and instead allow phpunit to handle that step during the bootstrap process (which is how Mantle CI works). This will enable other types of tests, such as testing plugins in isolation.

### Use Case

When a user is using Mantle CI for running tests, they should be able to have Mantle CI handle WordPress setup, copying files into the proper directories, and running tests.

**Comment by benpbolton** [comment]
Currently, setting `wordpress-version` to false would be required to skip WordPress bootstrapping.

**Comment by kevinfodness** [comment]
Fixed via #3
